services:
  # Web Service (Backend + Frontend)
  - type: web
    name: lablens
    env: docker
    region: oregon
    plan: free
    envVars:
      - key: PORT
        value: 5000
      - key: NODE_ENV
        value: production
    healthCheckPath: /api/health

