services:
  # Web Service (Backend + Frontend)
  - type: web
    name: lablens
    env: python
    region: oregon
    plan: free
    buildCommand: |
      # Install Python dependencies
      pip install -r ocr/requirements.txt
      # Install Node.js dependencies (including dev dependencies for build)
      npm install && cd client && npm install && cd ../server && npm install
      # Build frontend
      npm run build
    packages:
      - tesseract-ocr
      - poppler-utils
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: PYTHONUNBUFFERED
        value: 1
    healthCheckPath: /api/health

